### ISSUE TITLE
Stopped compiling after March 2024 update

### ISSUE THREAD

**Issue by dualarrow** [Spiikesan/BetterScarecrows#1]
After the March 2024 update, the following error is occuring during comple

(13:52:23) | [CSharp] Started Oxide.Compiler v successfully
(13:52:27) | Error while compiling BetterScarecrows: There is no argument given that corresponds to the required parameter 'maxRange' of 'BasePathFinder.GetBestRoamPosition(BaseNavigator, Vector3, Vector3, float, float)' | Line: 488, Pos: 61

**Comment by Spiikesan** [comment]
Hi,
Thanks for the report. I'm working on it.
